### ISSUE TITLE
Не працює

### ISSUE THREAD

**Issue by McSym** [jekahamster/coursera-parser#1]
Вітаю!

Не працює пункт 3. get-course-data. Отримую наступні помилки:

PS C:\Python310\Scripts\coursera-parser-main> python main.py get-course-data -u https://www.coursera.org/learn/technical-support-fundamentals/home/week/1
Loading week page
Loading week items
Traceback (most recent call last):
  File "C:\Python310\Scripts\coursera-parser-main\main.py", line 74, in <module>
    main(sys.argv[1:])
  File "C:\Python310\Scripts\coursera-parser-main\main.py", line 56, in main
    get_course_data(coursera_parser, url, DOWNLOAD_PATH)
  File "C:\Python310\Scripts\coursera-parser-main\main.py", line 17, in get_course_data
    course_data = parser.get_course_data(url)
  File "C:\Python310\Scripts\coursera-parser-main\coursera_parser.py", line 481, in get_course_data
    _wait_week_page_loading(self.driver)
  File "C:\Python310\Scripts\coursera-parser-main\coursera_parser.py", line 92, in _wait_week_page_loading
    wait.until(
  File "C:\Python310\lib\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

PS C:\Python310\Scripts\coursera-parser-main>

**Comment by jekahamster** [comment]
Hi! I just tested the parser on this course using the log you sent. Everything works, all 6 weeks were downloaded. Are you sure you logged in with the correct account? Or do you have a subscription to this course? The parser was created to automate the routine of saving videos if access is already granted. It was not created to hack anything. Also make sure you have downloaded the latest version of the project.

Привіт! Я щойно перевірив парсер на курсі з логу, який ви прикріпили. Все працює, завантажились всі 6 тижнів. Ви впевнені, що увійшли з правильного аккаунту? Або у вас є підписка на цей курс? Парсер створено для автоматизації процедури збереження відео (в майбтньому і інших типів занять), якщо доступ уже надано. Він не призначений для зламу курсу. Також перевірте, що у вас остання версія проєкту. 


Here is the sequence of commands I entered to make sure that I did not enter anything additional. Also, I want to add that the latest version is uploaded to the repository. In other words, I did not add anything that could affect parsing.
1. `python main.py login --email <COURSERA_EMAIL> --password <COURSERA_PASSWORD>`
2. `python main.py get-course-data -u https://www.coursera.org/learn/technical-support-fundamentals/home/week/1`

**Comment by McSym** [comment]
Привіт!

Спробував знову, але результат той самий. 
Акаунт точно правильний, підписка на цей курс є. Може це через те, що підписка на курс через грантову програму? Хоча зараз спробував на звичайній програмі - теж не вийшло. Папка downloads створюється, але в ній нічого не з'являється. Отже не з правами проблема. 

Ок. Спробував інший курс. Спеціально взяв безкоштовний. Записався на нього. https://www.coursera.org/learn/python-data-processing/home/week/1. Запустив парсер, вікно браузера відкривається, в акаунт входить, на курс переходить. І далі все. 3 хвилини чекаю - потім ті самі помилки.
![image](https://user-images.githubusercontent.com/46968663/229370403-04551a92-d63a-4f17-b8e5-04b2297d940b.png)
![image](https://user-images.githubusercontent.com/46968663/229370335-48998888-f68b-4a6b-b9be-4ff67bcf9681.png)
![image](https://user-images.githubusercontent.com/46968663/229370353-f5b5bd75-9a6c-4c4b-aa2d-836dea86ce22.png)

Зараз спробую взагалі інший акаунт створити.

**Comment by McSym** [comment]
Ні, з іншим акаунтом теж не працює. Пробував як безкоштовні курсти, так і за підпискою. Жаль, руками вантажити задовго.

**Comment by jekahamster** [comment]
I see the problem. Change the language of Coursera to English. It should help.

Бачу проблему. Змініть мову курсери на англійську. Повинно допомогти.

**Comment by McSym** [comment]
Ура! Працює. Дякую за парсер та допомогу. 

П.с. Можу також додати переклад англійською у свої повідомлення, якщо потрібно.

**Comment by jekahamster** [comment]
Дякую за знайдену помилку) Радий допомогти) 
Я розумію українську. Це для зручності користувачів з інших країн.
