### ISSUE TITLE
Seems like Coursera has changed the dropdown button to hover on Downloads

### ISSUE THREAD

**Issue by muhammad-obaidullah** [jekahamster/coursera-parser#3]
This commands seems not working for me `python main.py download-course -p <path_to_data>.json`. 
It throws TimeOutException error. However it seems like coursera has changed the dropdown/ button of download to just simply hover it. This might break some of the path elements. 

Could you please add the feature of extracting the transcript?

![image](https://github.com/jekahamster/coursera-parser/assets/22115788/d0693700-b133-48a5-b1e3-c5e654c94b58)

Issue:
![image](https://github.com/jekahamster/coursera-parser/assets/22115788/b5340b8e-e881-42e2-9197-27173e2d824e)

Ref from prev issue: My course is already in English Language.

**Comment by jekahamster** [comment]
The script also downloads the transcript, takes screenshots of the reading pages, and screenshots of the tasks (using up one attempt). I just tried it on the course you shared, and everything downloaded without any issues. On your screenshot, there seems to be some strange layout of the page with the video, but my page remained in the old version where the Download button is located below the video and is clicked with a dropdown menu. How did you get such a page? Perhaps you have a specific setting enabled? I have just added the latest version, but the paths in it remained the same.

**Comment by muhammad-obaidullah** [comment]
I see. Pretty strange. 

However for me it is still opening the course video in the same format. There is not any dropdown. Are you using Mac or Windows?

**Comment by jekahamster** [comment]
I'm using Windows

**Comment by muhammad-obaidullah** [comment]
Hmm.. I opened the coursera on Mac. It was same as on Windows. However it seems like you have old UI. Anyways, thanks.
